import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Navbar } from "./components/Navbar";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{

  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          {
            session?.user ? <Navbar/> : <></>
          }
          {children}
          <Toaster/>
        </div>
      </body>
    </html>
  );
}
